baseURL = "https://damlakeskekci.netlify.app/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"
[[menu.footer]]
URL = "#about"
name = "About"
weight = 2
[[menu.footer]]
URL = "#cv"
name = "Curriculum Vitae"
weight = 3
[[menu.footer]]
URL = "#projects"
name = "Projects"
weight = "4"
[[menu.footer]]
URL = "#contact"
name = "Contact"
weight = "5"
[[menu.header]]
URL = "#about"
name = "About"
weight = 2
[[menu.header]]
URL = "#cv"
name = "Curriculum Vitae"
weight = 3
[[menu.header]]
URL = "#projects"
name = "Projects"
weight = "4"
[[menu.header]]
URL = "#contact"
name = "Contact"
weight = "5"
[params]
googleTagManagerID = "GTM-000000"
sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]
[params.footer]
copyright = "© 2020 by Damla Keşkekci"
[params.footer.radity_logo]
_2x = ""
alt = ""
x = ""
[params.logo]
text1 = ""
text2 = ""
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"
